/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthTrackingIndexRouteImport } from './routes/_auth/tracking/index'
import { Route as AuthRemarketingsIndexRouteImport } from './routes/_auth/remarketings/index'
import { Route as AuthPixelsIndexRouteImport } from './routes/_auth/pixels/index'
import { Route as AuthGatewaysIndexRouteImport } from './routes/_auth/gateways/index'
import { Route as AuthFlowsIndexRouteImport } from './routes/_auth/flows/index'
import { Route as AuthFinanceiroIndexRouteImport } from './routes/_auth/financeiro/index'
import { Route as AuthClientsIndexRouteImport } from './routes/_auth/clients/index'
import { Route as AuthBotsIndexRouteImport } from './routes/_auth/bots/index'
import { Route as AuthRemarketingsNewRouteImport } from './routes/_auth/remarketings/new'
import { Route as AuthFlowsNewRouteImport } from './routes/_auth/flows/new'
import { Route as AuthBotsNewRouteImport } from './routes/_auth/bots/new'
import { Route as AuthRemarketingsRemarketingIdEditRouteImport } from './routes/_auth/remarketings/$remarketingId/edit'
import { Route as AuthFlowsFlowIdEditRouteImport } from './routes/_auth/flows/$flowId/edit'
import { Route as AuthBotsBotIdEditRouteImport } from './routes/_auth/bots/$botId/edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrackingIndexRoute = AuthTrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRemarketingsIndexRoute = AuthRemarketingsIndexRouteImport.update({
  id: '/remarketings/',
  path: '/remarketings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPixelsIndexRoute = AuthPixelsIndexRouteImport.update({
  id: '/pixels/',
  path: '/pixels/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGatewaysIndexRoute = AuthGatewaysIndexRouteImport.update({
  id: '/gateways/',
  path: '/gateways/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFlowsIndexRoute = AuthFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFinanceiroIndexRoute = AuthFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsIndexRoute = AuthClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBotsIndexRoute = AuthBotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRemarketingsNewRoute = AuthRemarketingsNewRouteImport.update({
  id: '/remarketings/new',
  path: '/remarketings/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFlowsNewRoute = AuthFlowsNewRouteImport.update({
  id: '/flows/new',
  path: '/flows/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBotsNewRoute = AuthBotsNewRouteImport.update({
  id: '/bots/new',
  path: '/bots/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRemarketingsRemarketingIdEditRoute =
  AuthRemarketingsRemarketingIdEditRouteImport.update({
    id: '/remarketings/$remarketingId/edit',
    path: '/remarketings/$remarketingId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFlowsFlowIdEditRoute = AuthFlowsFlowIdEditRouteImport.update({
  id: '/flows/$flowId/edit',
  path: '/flows/$flowId/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBotsBotIdEditRoute = AuthBotsBotIdEditRouteImport.update({
  id: '/bots/$botId/edit',
  path: '/bots/$botId/edit',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthDashboardRoute
  '/bots/new': typeof AuthBotsNewRoute
  '/flows/new': typeof AuthFlowsNewRoute
  '/remarketings/new': typeof AuthRemarketingsNewRoute
  '/bots/': typeof AuthBotsIndexRoute
  '/clients/': typeof AuthClientsIndexRoute
  '/financeiro/': typeof AuthFinanceiroIndexRoute
  '/flows/': typeof AuthFlowsIndexRoute
  '/gateways/': typeof AuthGatewaysIndexRoute
  '/pixels/': typeof AuthPixelsIndexRoute
  '/remarketings/': typeof AuthRemarketingsIndexRoute
  '/tracking/': typeof AuthTrackingIndexRoute
  '/bots/$botId/edit': typeof AuthBotsBotIdEditRoute
  '/flows/$flowId/edit': typeof AuthFlowsFlowIdEditRoute
  '/remarketings/$remarketingId/edit': typeof AuthRemarketingsRemarketingIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthDashboardRoute
  '/bots/new': typeof AuthBotsNewRoute
  '/flows/new': typeof AuthFlowsNewRoute
  '/remarketings/new': typeof AuthRemarketingsNewRoute
  '/bots': typeof AuthBotsIndexRoute
  '/clients': typeof AuthClientsIndexRoute
  '/financeiro': typeof AuthFinanceiroIndexRoute
  '/flows': typeof AuthFlowsIndexRoute
  '/gateways': typeof AuthGatewaysIndexRoute
  '/pixels': typeof AuthPixelsIndexRoute
  '/remarketings': typeof AuthRemarketingsIndexRoute
  '/tracking': typeof AuthTrackingIndexRoute
  '/bots/$botId/edit': typeof AuthBotsBotIdEditRoute
  '/flows/$flowId/edit': typeof AuthFlowsFlowIdEditRoute
  '/remarketings/$remarketingId/edit': typeof AuthRemarketingsRemarketingIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/bots/new': typeof AuthBotsNewRoute
  '/_auth/flows/new': typeof AuthFlowsNewRoute
  '/_auth/remarketings/new': typeof AuthRemarketingsNewRoute
  '/_auth/bots/': typeof AuthBotsIndexRoute
  '/_auth/clients/': typeof AuthClientsIndexRoute
  '/_auth/financeiro/': typeof AuthFinanceiroIndexRoute
  '/_auth/flows/': typeof AuthFlowsIndexRoute
  '/_auth/gateways/': typeof AuthGatewaysIndexRoute
  '/_auth/pixels/': typeof AuthPixelsIndexRoute
  '/_auth/remarketings/': typeof AuthRemarketingsIndexRoute
  '/_auth/tracking/': typeof AuthTrackingIndexRoute
  '/_auth/bots/$botId/edit': typeof AuthBotsBotIdEditRoute
  '/_auth/flows/$flowId/edit': typeof AuthFlowsFlowIdEditRoute
  '/_auth/remarketings/$remarketingId/edit': typeof AuthRemarketingsRemarketingIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/bots/new'
    | '/flows/new'
    | '/remarketings/new'
    | '/bots/'
    | '/clients/'
    | '/financeiro/'
    | '/flows/'
    | '/gateways/'
    | '/pixels/'
    | '/remarketings/'
    | '/tracking/'
    | '/bots/$botId/edit'
    | '/flows/$flowId/edit'
    | '/remarketings/$remarketingId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/bots/new'
    | '/flows/new'
    | '/remarketings/new'
    | '/bots'
    | '/clients'
    | '/financeiro'
    | '/flows'
    | '/gateways'
    | '/pixels'
    | '/remarketings'
    | '/tracking'
    | '/bots/$botId/edit'
    | '/flows/$flowId/edit'
    | '/remarketings/$remarketingId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/sign-in'
    | '/sign-up'
    | '/_auth/dashboard'
    | '/_auth/bots/new'
    | '/_auth/flows/new'
    | '/_auth/remarketings/new'
    | '/_auth/bots/'
    | '/_auth/clients/'
    | '/_auth/financeiro/'
    | '/_auth/flows/'
    | '/_auth/gateways/'
    | '/_auth/pixels/'
    | '/_auth/remarketings/'
    | '/_auth/tracking/'
    | '/_auth/bots/$botId/edit'
    | '/_auth/flows/$flowId/edit'
    | '/_auth/remarketings/$remarketingId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tracking/': {
      id: '/_auth/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof AuthTrackingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/remarketings/': {
      id: '/_auth/remarketings/'
      path: '/remarketings'
      fullPath: '/remarketings/'
      preLoaderRoute: typeof AuthRemarketingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pixels/': {
      id: '/_auth/pixels/'
      path: '/pixels'
      fullPath: '/pixels/'
      preLoaderRoute: typeof AuthPixelsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gateways/': {
      id: '/_auth/gateways/'
      path: '/gateways'
      fullPath: '/gateways/'
      preLoaderRoute: typeof AuthGatewaysIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/flows/': {
      id: '/_auth/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof AuthFlowsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/financeiro/': {
      id: '/_auth/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthFinanceiroIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients/': {
      id: '/_auth/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthClientsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bots/': {
      id: '/_auth/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof AuthBotsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/remarketings/new': {
      id: '/_auth/remarketings/new'
      path: '/remarketings/new'
      fullPath: '/remarketings/new'
      preLoaderRoute: typeof AuthRemarketingsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/flows/new': {
      id: '/_auth/flows/new'
      path: '/flows/new'
      fullPath: '/flows/new'
      preLoaderRoute: typeof AuthFlowsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bots/new': {
      id: '/_auth/bots/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof AuthBotsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/remarketings/$remarketingId/edit': {
      id: '/_auth/remarketings/$remarketingId/edit'
      path: '/remarketings/$remarketingId/edit'
      fullPath: '/remarketings/$remarketingId/edit'
      preLoaderRoute: typeof AuthRemarketingsRemarketingIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/flows/$flowId/edit': {
      id: '/_auth/flows/$flowId/edit'
      path: '/flows/$flowId/edit'
      fullPath: '/flows/$flowId/edit'
      preLoaderRoute: typeof AuthFlowsFlowIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bots/$botId/edit': {
      id: '/_auth/bots/$botId/edit'
      path: '/bots/$botId/edit'
      fullPath: '/bots/$botId/edit'
      preLoaderRoute: typeof AuthBotsBotIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthBotsNewRoute: typeof AuthBotsNewRoute
  AuthFlowsNewRoute: typeof AuthFlowsNewRoute
  AuthRemarketingsNewRoute: typeof AuthRemarketingsNewRoute
  AuthBotsIndexRoute: typeof AuthBotsIndexRoute
  AuthClientsIndexRoute: typeof AuthClientsIndexRoute
  AuthFinanceiroIndexRoute: typeof AuthFinanceiroIndexRoute
  AuthFlowsIndexRoute: typeof AuthFlowsIndexRoute
  AuthGatewaysIndexRoute: typeof AuthGatewaysIndexRoute
  AuthPixelsIndexRoute: typeof AuthPixelsIndexRoute
  AuthRemarketingsIndexRoute: typeof AuthRemarketingsIndexRoute
  AuthTrackingIndexRoute: typeof AuthTrackingIndexRoute
  AuthBotsBotIdEditRoute: typeof AuthBotsBotIdEditRoute
  AuthFlowsFlowIdEditRoute: typeof AuthFlowsFlowIdEditRoute
  AuthRemarketingsRemarketingIdEditRoute: typeof AuthRemarketingsRemarketingIdEditRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthBotsNewRoute: AuthBotsNewRoute,
  AuthFlowsNewRoute: AuthFlowsNewRoute,
  AuthRemarketingsNewRoute: AuthRemarketingsNewRoute,
  AuthBotsIndexRoute: AuthBotsIndexRoute,
  AuthClientsIndexRoute: AuthClientsIndexRoute,
  AuthFinanceiroIndexRoute: AuthFinanceiroIndexRoute,
  AuthFlowsIndexRoute: AuthFlowsIndexRoute,
  AuthGatewaysIndexRoute: AuthGatewaysIndexRoute,
  AuthPixelsIndexRoute: AuthPixelsIndexRoute,
  AuthRemarketingsIndexRoute: AuthRemarketingsIndexRoute,
  AuthTrackingIndexRoute: AuthTrackingIndexRoute,
  AuthBotsBotIdEditRoute: AuthBotsBotIdEditRoute,
  AuthFlowsFlowIdEditRoute: AuthFlowsFlowIdEditRoute,
  AuthRemarketingsRemarketingIdEditRoute:
    AuthRemarketingsRemarketingIdEditRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
